
GET http://localhost:1337/api/chanteurs
###
GET http://localhost:1337/api/musiques
###
GET http://localhost:1337/api/musiques?populate=*
###
POST http://localhost:1337/api/chanteurs
content-type: application/json

{
    "data": {
        "nom": "Bashung",
        "prenom": "Alain",
        "Date_de_naissance": "1947-12-01"
    }
}

###
POST http://localhost:1337/api/musiques
content-type: application/json

{
    "data": {
        "Titre": "Ethnic & Deep House Mix 2023",
        "lienYoutube": "https://www.youtube.com/watch?v=wVDgv2w6AcQ",
        "Favoris": true,
        "dateDeSortie": "2023-01-01",
        "CouleurDeFond": "#132562",
        "chanteur" : 5
    }
}