
GET http://localhost:1337/api/chanteurs
###
GET http://localhost:1337/api/musiques

###
GET http://localhost:1337/api/musiques?filters[Favoris][$eq]=true&populate=*
###
GET http://localhost:1337/api/musiques?populate=*
###
GET http://localhost:1337/api/musiques?populate=*&sort=createdAt:desc
###
POST http://localhost:1337/api/chanteurs
content-type: application/json

{
    "data": {
        "nom": "Bashung",
        "prenom": "Alain",
        "Date_de_naissance": "1947-12-01"
    }
}

###
POST http://localhost:1337/api/musiques
content-type: application/json

{
    "data": {
        "Titre": "Ethnic & Deep House Mix 2023",
        "lienYoutube": "https://www.youtube.com/watch?v=wVDgv2w6AcQ",
        "Favoris": true,
        "dateDeSortie": "2023-01-01",
        "CouleurDeFond": "#132562",
        "chanteur" : 5
    }
}


###
POST http://localhost:1337/api/musiques?populate=*
content-type: application/json

{
    "data":{
                
                "chanteur":1,
                "Titre" : "chanson",
                "CouleurDeFond" : "couleur",
                "dateDeSortie" : "2023-11-16",
                "lienYoutube" : "lienYoutube",
                "Favoris" : true
    }
}